spring:
  # 此配置会被sharding中datasource覆盖
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///reggie?useServerPrepStmts=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  shardingsphere:
    datasource:
      names:
        master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.86.130:3306/reggie?useServerPrepStmts=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#        url: jdbc:mysql://192.168.86.130:3306/reggie?useServerPrepStmts=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
#        use-ping-method: false
      slave:
        type: com.zaxxer.hikari.HikariDataSource
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.86.139:3306/reggie?useServerPrepStmts=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#        url: jdbc:mysql://192.168.86.139:3306/reggie?useServerPrepStmts=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
#        use-ping-method: false
    masterslave:
      load-balance-algorithm-type: round_robin
      # 数据源 bean 的名称，即 <bean id="{name}" ...>或 <bean name="{name}" ...>
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true
  redis:
#    host: 192.168.86.130
#    password: root
    database: 0
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  reactive:
    session:
      timeout: 60m
reggie:
  # 文件转储路径
  upload-path: /usr/local/reggie-pics/